# Basic Site Settings
locale                   : "en-US"
site_theme               : "default"
title                    : "Runze Wang"
title_separator          : "-"
name                     : &name "Runze Wang"
description              : &description "Runze Wang's academic homepage in statistical machine learning, computer vision, and robotics."
url                      : "https://rzkiller.github.io"
baseurl                  : ""
repository               : "RZkiller/RZkiller.github.io"

author:
  # Biographic information
  avatar           : "profile.png"
  name             : "Runze Wang"
  pronouns         :
  bio              : "M.S. student at Fudan University working on statistical machine learning, computer vision, and embodied intelligence."
  location         : "Shanghai, China"
  employer         : "Fudan University"
  uri              :
  email            : "24110980021@m.fudan.edu.cn"

  # Academic websites
  academia         :
  arxiv            :
  googlescholar    :
  inspire-hep      :
  impactstory      :
  orcid            :
  semantic         :
  ssrn             :
  pubmed           :
  researchgate     :
  scopus           :
  zotero           :

  # Repositories and software development
  bitbucket        :
  codepen          :
  dribbble         :
  github           : "RZkiller"
  kaggle           :
  stackoverflow    :

  # Social media
  artstation       :
  bluesky          :
  facebook         :
  flickr           :
  foursquare       :
  goodreads        :
  google_plus      :
  keybase          :
  instagram        :
  lastfm           :
  linkedin         :
  mastodon         :
  medium           :
  pinterest        :
  soundcloud       :
  steam            :
  telegram         :
  tumblr           :
  twitter          :
  vine             :
  weibo            :
  wikipedia        :
  xing             :
  youtube          :
  zhihu            :

# SEO Related
social:
  type                   : "Person"
  name                   : "Runze Wang"
  links:
    - "https://github.com/RZkiller"

timezone: Asia/Shanghai
